#!/usr/bin/env python3
"""Final assembly: lock the resolved visuals to the real voiceover timeline.

Unlike pixabay-video-producer's assemble_video.py (which just concatenates
scenes back to back), this script's beats already carry their exact
start/end from the real transcript timing — the voiceover audio is the
master clock. Each beat's resolved clip (already downloaded from Pixabay,
generated by an AI video tool, or hybrid-composited by apply_overlay.py) is
normalized and trimmed/looped to its own slot, the beats are concatenated in
order, and the finished video is padded/trimmed to match the narration
track exactly before muxing it in. An optional music bed gets ducked under
the narration with sidechain compression and loudness-normalized.

Beats manifest format (list, in order — see build_beats.py for the shape
before "file" is added once each beat's visual is resolved):

    [
      {"start": 0.0, "end": 4.1, "duration": 4.1, "file": "work/beat_000.mp4"},
      {"start": 4.1, "end": 7.6, "duration": 3.5, "file": "work/beat_001.mp4"}
    ]

Usage:
    python3 assemble_from_beats.py --beats beats_resolved.json \
        --narration voiceover.mp3 --aspect 16:9 --output final.mp4 \
        [--music soundtrack.mp3 --music-volume 0.25]
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile

PRESET_ASPECTS = {
    "9:16": (1080, 1920),
    "16:9": (1920, 1080),
    "1:1": (1080, 1080),
    "4:5": (1080, 1350),
}


def resolve_resolution(aspect: str):
    if aspect in PRESET_ASPECTS:
        return PRESET_ASPECTS[aspect]
    if "x" in aspect.lower():
        w, h = aspect.lower().split("x")
        return int(w), int(h)
    raise ValueError(f"Unknown --aspect '{aspect}'. Use 9:16, 16:9, 1:1, 4:5, or WIDTHxHEIGHT.")


def run(cmd):
    result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"Command failed ({' '.join(cmd)}):\n{result.stdout}")
    return result.stdout


def probe_duration(path: str) -> float:
    out = run(["ffprobe", "-v", "error", "-show_entries", "format=duration",
               "-of", "default=noprint_wrappers=1:nokey=1", path])
    return float(out.strip())


def normalize_beat(src: str, duration: float, width: int, height: int, fps: int, out_path: str):
    src_duration = probe_duration(src)
    vf = f"scale={width}:{height}:force_original_aspect_ratio=increase,crop={width}:{height},setsar=1,fps={fps}"
    if src_duration < duration:
        cmd = ["ffmpeg", "-y", "-stream_loop", "-1", "-i", src, "-t", str(duration),
               "-vf", vf, "-an", "-c:v", "libx264", "-pix_fmt", "yuv420p", out_path]
    else:
        cmd = ["ffmpeg", "-y", "-i", src, "-t", str(duration),
               "-vf", vf, "-an", "-c:v", "libx264", "-pix_fmt", "yuv420p", out_path]
    run(cmd)


def concat_beats(normalized: list, output: str, fps: int):
    with tempfile.NamedTemporaryFile("w", suffix=".txt", delete=False) as f:
        for path in normalized:
            f.write(f"file '{os.path.abspath(path)}'\n")
        list_path = f.name
    try:
        run(["ffmpeg", "-y", "-f", "concat", "-safe", "0", "-i", list_path,
             "-r", str(fps), "-c:v", "libx264", "-pix_fmt", "yuv420p", output])
    finally:
        os.unlink(list_path)


def pad_or_trim_to_duration(video: str, target_duration: float, output: str):
    video_duration = probe_duration(video)
    if abs(video_duration - target_duration) < 0.05:
        shutil.copy(video, output)
        return
    if video_duration < target_duration:
        pad = target_duration - video_duration
        run(["ffmpeg", "-y", "-i", video, "-vf",
             f"tpad=stop_mode=clone:stop_duration={pad}", "-c:v", "libx264", "-pix_fmt", "yuv420p", output])
    else:
        run(["ffmpeg", "-y", "-i", video, "-t", str(target_duration),
             "-c:v", "libx264", "-pix_fmt", "yuv420p", output])


def mux_final(video: str, narration: str, music: str, music_volume: float, output: str):
    duration = probe_duration(narration)
    if music:
        filter_complex = (
            f"[2:a]volume={music_volume}[music];"
            "[1:a]asplit=2[narr][sc];"
            "[music][sc]sidechaincompress=threshold=0.05:ratio=8:attack=5:release=300[ducked];"
            "[ducked][narr]amix=inputs=2:duration=first:weights=1 1,loudnorm=I=-14:TP=-1:LRA=11[aout]"
        )
        cmd = ["ffmpeg", "-y", "-i", video, "-i", narration, "-stream_loop", "-1", "-i", music,
               "-filter_complex", filter_complex, "-map", "0:v", "-map", "[aout]",
               "-t", str(duration), "-c:v", "copy", "-c:a", "aac", output]
    else:
        cmd = ["ffmpeg", "-y", "-i", video, "-i", narration,
               "-af", "loudnorm=I=-16:TP=-1:LRA=11",
               "-map", "0:v", "-map", "1:a", "-t", str(duration),
               "-c:v", "copy", "-c:a", "aac", output]
    run(cmd)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--beats", required=True, help="JSON manifest; each beat needs start/end/duration/file")
    parser.add_argument("--narration", required=True, help="The real voiceover audio — the timeline's master clock")
    parser.add_argument("--music", default=None, help="Optional music bed, ducked under the narration")
    parser.add_argument("--music-volume", type=float, default=0.25)
    parser.add_argument("--aspect", default="16:9")
    parser.add_argument("--fps", type=int, default=30)
    parser.add_argument("--output", required=True)
    parser.add_argument("--workdir", default=None)
    args = parser.parse_args()

    for tool in ("ffmpeg", "ffprobe"):
        if shutil.which(tool) is None:
            print(f"{tool} not found on PATH.", file=sys.stderr)
            sys.exit(1)

    with open(args.beats, encoding="utf-8") as f:
        beats = json.load(f)
    if not beats:
        print("Beats manifest is empty.", file=sys.stderr)
        sys.exit(1)
    for i, beat in enumerate(beats):
        if "file" not in beat:
            print(f"Beat {i} has no resolved 'file' — resolve every beat's visual before assembling.", file=sys.stderr)
            sys.exit(1)

    width, height = resolve_resolution(args.aspect)
    workdir = args.workdir or tempfile.mkdtemp(prefix="voiceover_assemble_")
    os.makedirs(workdir, exist_ok=True)

    normalized = []
    for i, beat in enumerate(beats):
        out_path = os.path.join(workdir, f"beat_{i:03d}.mp4")
        normalize_beat(beat["file"], float(beat["duration"]), width, height, args.fps, out_path)
        normalized.append(out_path)
        print(f"Normalized beat {i+1}/{len(beats)} ({beat['duration']:.2f}s)", file=sys.stderr)

    concatenated = os.path.join(workdir, "concatenated.mp4")
    concat_beats(normalized, concatenated, args.fps)

    narration_duration = probe_duration(args.narration)
    padded = os.path.join(workdir, "padded.mp4")
    pad_or_trim_to_duration(concatenated, narration_duration, padded)

    mux_final(padded, args.narration, args.music, args.music_volume, args.output)

    print(json.dumps({"output": args.output, "resolution": f"{width}x{height}",
                       "beats": len(beats), "duration": narration_duration}))


if __name__ == "__main__":
    main()
